# Generated by Django 4.1.5 on 2023-01-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_auto_20230124_2209"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="descricao",
            field=models.CharField(default="descricao", max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="produtos",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
