# Generated by Django 4.1.5 on 2023-01-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_produtos_descricao_alter_produtos_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="descricao",
            field=models.CharField(max_length=513),
        ),
    ]
