# Generated by Django 4.1.5 on 2023-01-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_produtos_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="descricao",
            field=models.CharField(max_length=512),
        ),
    ]
