# Generated by Django 4.1.5 on 2023-01-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_produtos_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="precobase",
            field=models.DecimalField(decimal_places=2, default=12.23, max_digits=8),
            preserve_default=False,
        ),
    ]
