# Generated by Django 4.1.5 on 2023-01-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_remove_produtos_precobase"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="img_url",
            field=models.CharField(
                default="https://www.w3schools.com/w3images/jeans3.jpg", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produtos",
            name="tipo",
            field=models.CharField(default="informatica", max_length=100),
            preserve_default=False,
        ),
    ]
