# Generated by Django 4.1.5 on 2023-02-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_produtos_img_url_produtos_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="estado",
            field=models.CharField(default="ativo", max_length=100),
        ),
    ]
