# Generated by Django 4.1.5 on 2023-02-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_produtosinfo"),
    ]

    operations = [
        migrations.AlterModelOptions(name="produtosinfo", options={},),
    ]
