# Generated by Django 4.1.5 on 2023-02-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_alter_produtosinfo_options"),
    ]

    operations = [
        migrations.RemoveField(model_name="produtosinfo", name="produtos_user",),
        migrations.RemoveField(model_name="produtosinfo", name="produtos_user_groups",),
        migrations.AlterModelTable(name="produtosinfo", table=None,),
    ]
