# Generated by Django 4.1.5 on 2023-02-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_remove_produtosinfo_produtos_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="produtosinfo", options={"managed": False},),
    ]
