# Generated by Django 4.1.5 on 2023-02-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_alter_produtosinfo_options"),
    ]

    operations = [
        migrations.AlterModelTable(name="produtosinfo", table="produtosInfo",),
    ]
