# Generated by Django 4.1.5 on 2023-02-01 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_alter_produtosinfo_table"),
    ]

    operations = [
        migrations.DeleteModel(name="ProdutosInfo",),
    ]
