# Generated by Django 4.1.5 on 2023-02-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_delete_produtosinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdutosInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=512)),
                ("tipo", models.CharField(max_length=100)),
                ("estado", models.CharField(default="ativo", max_length=100)),
                ("img_url", models.CharField(max_length=100)),
            ],
            options={"db_table": "store_produtosInfo", "managed": False,},
        ),
    ]
