# Generated by Django 4.1.5 on 2023-02-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_produtosinfo"),
    ]

    operations = [
        migrations.DeleteModel(name="ProdutosInfo",),
        migrations.AddField(
            model_name="produtos",
            name="parceiro",
            field=models.BooleanField(default=False),
        ),
    ]
