# Generated by Django 4.1.5 on 2023-02-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_delete_produtosinfo_produtos_parceiro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="parceiro",
            field=models.IntegerField(default=0),
        ),
    ]
