# Generated by Django 4.1.5 on 2023-01-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrinho",
            name="data",
            field=models.DateTimeField(default="2023-01-27"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carrinho",
            name="prod_id",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carrinho",
            name="quantidade",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carrinho",
            name="user_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
