# Generated by Django 4.1.5 on 2023-01-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0002_alter_carrinho_data_alter_vendas_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocoes",
            name="percentagem",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
