# Generated by Django 4.1.5 on 2023-01-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0005_carrinho_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrinho",
            name="session_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="carrinho", name="user_id", field=models.IntegerField(null=True),
        ),
    ]
