# Generated by Django 4.1.5 on 2023-02-01 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0006_alter_carrinho_session_id_alter_carrinho_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="vendas_estado",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vendas.estados"
            ),
        ),
    ]
