# Generated by Django 4.1.5 on 2023-02-01 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0007_estados_alter_vendas_estado_estado"),
    ]

    operations = [
        migrations.RemoveField(model_name="vendas_estado", name="estado",),
    ]
