# Generated by Django 4.1.5 on 2023-02-01 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0008_remove_vendas_estado_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendas_estado",
            name="estado",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendas.estados",
            ),
            preserve_default=False,
        ),
    ]
