# Generated by Django 4.1.5 on 2023-02-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0009_vendas_estado_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produtos_Stock_Preco_Prom",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("prod_id", models.IntegerField()),
                ("preco_base", models.DecimalField(decimal_places=2, max_digits=6)),
                ("promotion", models.DecimalField(decimal_places=2, max_digits=6)),
                ("preco_final", models.DecimalField(decimal_places=2, max_digits=6)),
                ("validade", models.DateTimeField()),
            ],
            options={"db_table": "vendas_produtos_stock_preco_prom", "managed": False,},
        ),
        migrations.AlterField(
            model_name="promocoes",
            name="data_exp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
